In [1]:
from sqlalchemy import create_engine


# DB_USER = "your_username"
# DB_PASSWORD = "your_password"
# DB_HOST = "localhost"
# DB_NAME = "ipl"
engine = create_engine(
    f"mysql+pymysql://{DB_USER}:{DB_PASSWORD}@{DB_HOST}/{DB_NAME}"
)
print("Connected Successfully")

Connected Successfully

In [2]:
import pandas as pd

matches = pd.read_csv(r"C:\Users\asus\Downloads\matches.csv")

matches.head()

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan

In [6]:
import pymysql

conn = pymysql.connect(
    host="localhost",
    user="root",
    password="Piyush@125",
    database="ipl_analysis"
)

print("Connected")

Connected

In [7]:
engine.connect()

In [9]:
matches.rename(columns={"id": "match_id"}, inplace=True)

In [10]:
print(matches.columns)

Index(['match_id', 'season', 'city', 'date', 'match_type', 'player_of_match',
       'venue', 'team1', 'team2', 'toss_winner', 'toss_decision', 'winner',
       'result', 'result_margin', 'target_runs', 'target_overs', 'super_over',
       'method', 'umpire1', 'umpire2'],
      dtype='str')

In [11]:
matches.to_sql(
    name="matches",
    con=engine,
    if_exists="append",
    index=False
)

print("Matches Imported Successfully")

Matches Imported Successfully

In [27]:
import pandas as pd

deliveries = pd.read_csv(r"C:\Users\asus\Downloads\deliveries.csv\deliveries.csv")

In [28]:
deliveries.head()

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,1,1,legbyes,0,NaN,NaN,NaN
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,1,1,wides,0,NaN,NaN,NaN
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN

In [29]:
deliveries.rename(columns={
    "over": "over_no",
    "ball": "ball_no"
}, inplace=True)

In [30]:
print(deliveries.columns.tolist())

['match_id', 'inning', 'batting_team', 'bowling_team', 'over_no', 'ball_no', 'batter', 'bowler', 'non_striker', 'batsman_runs', 'extra_runs', 'total_runs', 'extras_type', 'is_wicket', 'player_dismissed', 'dismissal_kind', 'fielder']

In [43]:
deliveries.to_sql(
    name="deliveries",
    con=engine,
    if_exists="append",
    index=False,
    chunksize=1000
)

print("Deliveries Imported Successfully")

Deliveries Imported Successfully

In [32]:
import pandas as pd

teams = pd.read_csv(r"C:\Users\asus\Desktop\IPL Data\teams_data.csv")

In [33]:
teams.head()

,team_id,team_name,team_name_short,image_url
0,1,Royal Challengers Bangalore,RCB,https://documents.iplt20.com/ipl/RCB/Logos/Log...
1,2,Sunrisers Hyderabad,SRH,https://documents.iplt20.com/ipl/SRH/Logos/Log...
2,3,Mumbai Indians,MI,https://documents.iplt20.com/ipl/MI/Logos/Logo...
3,4,Rising Pune Supergiant,RPS,https://ipl-stats-sports-mechanic.s3.ap-south-...
4,5,Gujarat Lions,GL,https://ipl-stats-sports-mechanic.s3.ap-south-...

In [34]:
teams.to_sql(
    name="teams",
    con=engine,
    if_exists="append",
    index=False
)

16

In [35]:
players = pd.read_csv(
    r"C:\Users\asus\Desktop\IPL Data\players-data-updated.csv",
    encoding="latin1"
)

In [36]:
players.head()

,player_id,player_name,bat_style,bowl_style,field_pos,player_full_name,player_name2,player_image
0,6730,Mohsin Khan,Left hand Bat,Left arm Medium fast,NaN,Mohsin Khan,Mohsin Khan,NaN
1,22,Rashid Khan,Right hand Bat,Legbreak Googly,,Rashid Khan Arman,Rashid Khan,https://www.espncricinfo.com/cricketers/rashid...
2,590,K Rabada,Left hand Bat,Right arm Fast,,Kagiso Rabada,Kagiso Rabada,https://ipl-stats-sports-mechanic.s3.ap-south-...
3,1424,SN Khan,Right hand Bat,Legbreak,,Sarfaraz Naushad Khan,Sarfaraz Naushad,NaN
4,963,MN Samuels,Right hand Bat,Right arm Offbreak,,Marlon Nathaniel Samuels,Marlon Nathaniel,NaN

In [37]:
players.to_sql(
    name="players",
    con=engine,
    if_exists="append",
    index=False
)

772

In [39]:
len(matches)

1095

In [40]:
len(deliveries)

260920

In [41]:
len(teams)

16

In [42]:
len(players)

772